---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aquasec-cc-kustomize
images:
- name: registry.aquasec.com/cc-premium:20230130
  newTag: '20230201'
resources:
- ./config-dev/dev-01/aqua00/aquasec-core/kustomized-manifest.yaml