#! /usr/bin/make -f

kustomize_image=argocd
kustomize_namespace=argoproj
kustomize_tag=v2.4.12
kustomize_name=$(kustomize_namespace)-$(kustomize_image)-$(kustomize_tag)-kustomize
kustomize_registry=docker.com
kustomize_scm_prefix=git::https://bitbucket.com/scm/~$(USER)
kustomize_scm_ref=