apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.path.v4.4.1: /usr/local/bin/kustomize
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
  kustomize.buildOptions: --enable-helm
  kustomize.buildOptions.v4.4.1: --output /tmp
  configManagementPlugins: |
    - name: kustomize-build-with-helm
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]