---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.8.3
    chart: argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd