---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-premium-kustomize
  namespace: argocd
  annotations:
    # argocd-image-updater.argoproj.io/cc.force-update: "true"
    # argocd-image-updater.argoproj.io/cc.pull-secret: pullsecret:argocd/aqua-registry-secret
    # argocd-image-updater.argoproj.io/image-list: cc=registry.aquasec.com/cc-premium
spec:
  destination:
    name: ''
    namespace: aquasec-cc-kustomize
    server: 'https://kubernetes.default.svc'
  source:
    path: cc-image-updater/src/aquasec-cc/kustomization.yaml
    repoURL: https://github.com/rootleveltech/cc-kustomize
    targetRevision: testing
  project: default
  syncPolicy:
    automated: null
    syncOptions:
    - CreateNamespace=true